name: Create Subtask on Custom Field Change

on:
  workflow_dispatch:

jobs:
  create-subtask:
    runs-on: ubuntu-latest
    steps:
      - name: Check if custom field changed to desired value
        id: check_custom_field
        uses: actions/github-script@v4
        with:
          script: |
            const payload = context.payload;
            const desiredCustomFieldValue = 'YourDesiredValue'; // Replace with your desired custom field value
            const customFieldValue = payload.changes?.customfield_10063?.newValue; // Adjust the field ID as per your Jira setup

            if (customFieldValue === desiredCustomFieldValue) {
              console.log(`Custom field value changed to ${customFieldValue}. Proceeding to create subtask...`);
              return customFieldValue;
            } else {
              console.log(`Custom field value is ${customFieldValue}. No action required.`);
              return null;
            }

      - name: Create Jira subtask
        if: steps.check_custom_field.outputs == 'YourDesiredValue'
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: 'https://your-jira-instance.atlassian.net/rest/api/3'
        run: |
          ISSUE_ID=$(jq -r '.issue.id' < $GITHUB_EVENT_PATH)
          JIRA_ISSUE_KEY=$(curl -s --request POST \
            --url "$JIRA_BASE_URL/issue" \
            --header 'Authorization: Basic '$JIRA_API_TOKEN \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "fields": {
                "project": {
                  "key": "TT"
                },
                "parent": {
                  "id": "10007"
                },
                "summary": "Subtask summary",
                "issuetype": {
                  "id": "10008"
                }
              }
            }' | jq -r '.key')
          echo "Created subtask with key $JIRA_ISSUE_KEY"
