name: Create Jira Subtasks

on:
  workflow_dispatch:

jobs:
  create-subtasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Jira subtask creation
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: 'https://infinityink.atlassian.net'  # Replace with your Jira instance URL
        run: |
          # Extract necessary information (issue key, custom field value, etc.) from your workflow trigger event
          # You might need to parse this information from the payload or use GitHub Actions context

          # Example script to create subtasks using Jira REST API
          issueKey="TT-41"
          customFieldValue="yes"

          # Use curl or any HTTP client to interact with Jira API
          # Replace with actual API endpoint and payload
          curl -X POST \
            -H "Authorization: Basic $(echo -n your_jira_username:$JIRA_API_TOKEN | base64)" \
            -H "Content-Type: application/json" \
            -d '{
              "fields": {
                "parent": {
                  "key": "'"TT-41"'"
                },
                "summary": "Subtask 1",
                "description": "Description of Subtask 1",
                "issuetype": {
                  "name": "Sub-task"
                }
              }
            }' \
            "$JIRA_BASE_URL/rest/api/2/issue/"

          curl -X POST \
            -H "Authorization: Basic $(echo -n your_jira_username:$JIRA_API_TOKEN | base64)" \
            -H "Content-Type: application/json" \
            -d '{
              "fields": {
                "parent": {
                  "key": "'"TT-41"'"
                },
                "summary": "Subtask 2",
                "description": "Description of Subtask 2",
                "issuetype": {
                  "name": "Sub-task"
                }
              }
            }' \
            "$JIRA_BASE_URL/rest/api/2/issue/"

