name: Create Jira Subtasks

on:
  workflow_dispatch:

jobs:
  create-subtasks:
    runs-on: ubuntu-latest

    steps:
      - name: Check for custom field change
        id: check_custom_field
        uses: atlassian/gajira-check-issue@master
        with:
          server-url: 'https://infinityink.atlassian.net'
          issue-key: 'TT-41'
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          api-token: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create subtasks if necessary
        if: steps.check_custom_field.outputs.custom_field_value == 'Yes'
        run: |
          # Script to create subtasks using Jira REST API
          issueKey="TT-41"
          subtaskSummary1="Subtask 1"
          subtaskSummary2="Subtask 2"
          apiUrl="https://infinityink.atlassian.net/rest/api/2/issue/"

          # Create subtask 1
          curl -X POST \
            -H "Authorization: Basic $(echo -n ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} | base64)" \
            -H "Content-Type: application/json" \
            -d '{
              "fields": {
                "parent": {
                  "key": "'"TT-41"'"
                },
                "summary": "'"$subtaskSummary1"'",
                "issuetype": {
                  "name": "Sub-task"
                }
              }
            }' \
            "$apiUrl"

          # Create subtask 2
          curl -X POST \
            -H "Authorization: Basic $(echo -n ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} | base64)" \
            -H "Content-Type: application/json" \
            -d '{
              "fields": {
                "parent": {
                  "key": "'"TT-41"'"
                },
                "summary": "'"$subtaskSummary2"'",
                "issuetype": {
                  "name": "Sub-task"
                }
              }
            }' \
            "$apiUrl"
